import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { LayoutDashboard, CreditCard, Files, ReceiptText, WalletCards, BookOpen, ChartNoAxesCombined, History, LogOut, Menu, Settings, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from '@/components/ui/sheet';
import { Audit, Catalog, Money, Reports } from './pages';
import { CatalogManager, DraftActivity, ExpenseForm, MoneyForm, PaymentRequests, RegistryUpload, TelegramLinkManager, UserManager } from './forms';
import './styles.css';

const nav = [
  ['overview', 'Обзор', LayoutDashboard], ['requests', 'Карты к оплате', CreditCard], ['registries', 'Реестры оплат', Files], ['expenses', 'Расходы', ReceiptText], ['money', 'Движение денег', WalletCards],
  ['catalog', 'Справочники', BookOpen], ['reports', 'Отчёты', ChartNoAxesCombined], ['audit', 'История действий', History]
];
const roleNames = { chief: 'Главный администратор', operator: 'Операционист', collector: 'Сборщик', accountant: 'Бухгалтер', sysadmin: 'Системный администратор', auditor: 'Аудитор' };
const rub = new Intl.NumberFormat('ru-RU', { style: 'currency', currency: 'RUB', minimumFractionDigits: 2 });
async function api(path, body) { const response = await fetch(path, body ? { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json', 'X-CSRF': '1' }, body: JSON.stringify(body) } : { credentials: 'same-origin', headers: { 'X-CSRF': '1' } }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Не удалось выполнить действие'); return data; }

function Login({ onLogin }) {
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(event) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(''); try { await api('/login', Object.fromEntries(form)); await onLogin(); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <main className="grid min-h-[100dvh] max-w-7xl grid-cols-1 items-center gap-10 px-6 py-10 lg:grid-cols-[1fr_520px] lg:px-16"><section><div className="mb-10 flex items-center gap-3 text-sm font-medium"><span className="grid size-11 place-items-center rounded-xl bg-primary text-lg font-bold text-primary-foreground">М</span><span>Металлист<br /><strong>Платформа</strong></span></div><p className="mb-3 text-xs font-semibold tracking-[.14em] text-primary uppercase">Рабочий кабинет</p><h1 className="max-w-xl text-5xl font-semibold tracking-[-.05em] text-balance lg:text-7xl">Деньги и обязательства на виду.</h1><p className="mt-5 max-w-xl text-lg leading-7 text-muted-foreground">Реестры, наличные и расходы в одном месте. Каждое денежное действие проходит отдельное подтверждение.</p></section><Card className="rounded-3xl border-border shadow-[0_24px_60px_rgba(24,37,29,.055)]"><CardHeader><CardTitle className="text-2xl">Войти в кабинет</CardTitle><CardDescription>Для демо используйте логин chief. Пароль задаётся отдельно.</CardDescription></CardHeader><CardContent><form className="grid gap-5" onSubmit={submit}><label className="grid gap-2 text-sm font-medium">Логин<Input name="login" autoComplete="username" required /></label><label className="grid gap-2 text-sm font-medium">Пароль<Input name="password" type="password" autoComplete="current-password" required /></label>{error && <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}<Button size="lg" type="submit" disabled={busy}>{busy ? 'Вход…' : 'Войти'}</Button></form></CardContent></Card></main>;
}

function Overview({ report }) { const metrics = [['Деньги на картах и в кассах', report.summary.card_cash, 'Где находятся сопровождаемые деньги'], ['К возврату мерчантам', report.summary.merchant_payable, 'Подтверждённый долг по реестрам'], ['Заработанная комиссия', report.summary.commission_revenue, 'Выручка без транзитных сумм'], ['Прибыль', report.summary.profit, 'Доходы за вычетом расходов']]; return <><div className="mb-8"><h1 className="text-4xl font-semibold tracking-[-.045em]">Обзор</h1><p className="mt-2 max-w-2xl text-muted-foreground">Главные суммы из подтверждённых операций. Черновики не меняют эти показатели.</p></div><div className="grid gap-4 sm:grid-cols-2">{metrics.map(([label, value, detail]) => <Card key={label} className="min-h-36 rounded-2xl"><CardContent className="flex h-full min-h-36 flex-col justify-between p-6"><p className="text-sm text-muted-foreground">{label}</p><strong className="font-mono text-2xl tracking-[-.05em] lg:text-3xl">{rub.format(Number(value || 0))}</strong><small className="text-xs text-muted-foreground">{detail}</small></CardContent></Card>)}</div><section className="mt-9"><h2 className="mb-4 text-xl font-semibold">Что сделать сейчас</h2><div className="grid gap-3 sm:grid-cols-2"><Card className="rounded-2xl"><CardContent className="p-5"><strong>Подготовить карты к оплате</strong><p className="mt-2 text-sm text-muted-foreground">Создать запрос и скачать файл для мерчанта</p></CardContent></Card><Card className="rounded-2xl"><CardContent className="p-5"><strong>Добавить расход</strong><p className="mt-2 text-sm text-muted-foreground">Сумма, тип и дата. Остальные поля по необходимости.</p></CardContent></Card></div></section></>; }

function AccountPage() { const [error, setError] = useState(''), [busy, setBusy] = useState(false), [done, setDone] = useState(false); async function submit(event) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(''); try { await api('/api/password', Object.fromEntries(form)); setDone(true); } catch (e) { setError(e.message); } finally { setBusy(false); } } return <><div className="mb-8"><h1 className="text-4xl font-semibold tracking-[-.045em]">Настройки входа</h1><p className="mt-2 max-w-2xl text-muted-foreground">После смены пароля все прежние сеансы будут завершены.</p></div><Card className="max-w-xl rounded-2xl"><CardHeader><CardTitle>Сменить пароль</CardTitle><CardDescription>Новый пароль должен состоять минимум из 16 символов.</CardDescription></CardHeader><CardContent>{done ? <Alert><AlertDescription>Пароль изменён. Войдите заново, чтобы продолжить.</AlertDescription></Alert> : <form className="grid gap-5" onSubmit={submit}><label className="grid gap-2 text-sm font-medium">Текущий пароль<Input name="current" type="password" autoComplete="current-password" required /></label><label className="grid gap-2 text-sm font-medium">Новый пароль<Input name="new" type="password" autoComplete="new-password" minLength="16" required /></label>{error && <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}<Button type="submit" disabled={busy}>{busy ? 'Сохранение…' : 'Сохранить новый пароль'}</Button></form>}</CardContent></Card></>; }

function App() {
  const [user, setUser] = useState(null); const [report, setReport] = useState(null); const [page, setPage] = useState('overview'); const [error, setError] = useState('');
  async function load() { try { const me = await api('/api/me'); setUser(me); setReport(await api('/api/report')); } catch { setUser(null); } }
  useEffect(() => { load(); }, []);
  if (!user) return <Login onLogin={load} />;
  const Nav = ({ mobile = false }) => <nav className="grid gap-1">{nav.map(([id, label, Icon]) => <Button key={id} variant={page === id ? 'secondary' : 'ghost'} className="justify-start" onClick={() => { setPage(id); setError(''); }}><Icon className="size-4" />{label}</Button>)}{mobile && <Button variant="ghost" className="justify-start" onClick={() => setPage('account')}><Settings className="size-4" />Настройки входа</Button>}</nav>;
  async function logout() { try { await api('/logout', {}); location.reload(); } catch (err) { setError(err.message); } }
  const pages = { requests: <PaymentRequests role={user.Role} />, registries: <RegistryUpload role={user.Role} />, expenses: <><ExpenseForm /><DraftActivity role={user.Role} /></>, money: <><MoneyForm role={user.Role} /><Money /><DraftActivity role={user.Role} kind="money" title="Черновики и проведённые операции" /></>, catalog: <><Catalog /><CatalogManager role={user.Role} /><UserManager role={user.Role} /><TelegramLinkManager role={user.Role} /></>, reports: <Reports role={user.Role} />, audit: <Audit />, account: <AccountPage /> };
  return <div className="min-h-[100dvh] bg-background lg:grid lg:grid-cols-[250px_1fr]"><aside className="hidden border-r bg-card p-4 lg:flex lg:flex-col"><div className="mb-8 flex items-center gap-3 px-3 pt-3"><span className="grid size-10 place-items-center rounded-xl bg-primary font-bold text-primary-foreground">М</span><span className="text-sm">Металлист<br /><strong>Платформа</strong></span></div><p className="mb-2 px-3 text-xs font-semibold tracking-[.12em] text-muted-foreground uppercase">Работа</p><Nav /><div className="mt-auto border-t p-3"><p className="mb-3 text-sm font-semibold">{user.Name}</p><Button variant="ghost" className="w-full justify-start" onClick={() => setPage('account')}><Settings className="size-4" />Настройки входа</Button><Button variant="ghost" className="w-full justify-start" onClick={logout}><LogOut className="size-4" />Выйти</Button></div></aside><main><header className="flex h-16 items-center justify-between border-b px-4 lg:px-12"><Sheet><SheetTrigger asChild><Button variant="outline" size="icon" className="lg:hidden"><Menu /></Button></SheetTrigger><SheetContent side="left" className="w-72"><SheetHeader><SheetTitle>Металлист Платформа</SheetTitle></SheetHeader><div className="mt-6"><Nav mobile /></div></SheetContent></Sheet><span className="text-sm text-muted-foreground">{nav.find(([id]) => id === page)?.[1] || 'Настройки входа'}</span><Badge variant="secondary">{roleNames[user.Role] || 'Пользователь'}</Badge></header><div className="mx-auto max-w-[1440px] px-5 py-8 lg:px-14 lg:py-12">{error && <Alert variant="destructive" className="mb-5"><AlertDescription>{error}</AlertDescription></Alert>}{page === 'overview' && report ? <Overview report={report} /> : pages[page] || <AccountPage />}</div></main></div>;
}

createRoot(document.getElementById('root')).render(<App />);
