import React, { useEffect, useState } from 'react';
import { request, userError } from './api-errors';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Alert, AlertDescription } from '@/components/ui/alert';

const status = { draft: ['Черновик', 'secondary'], preview: ['Ожидает подтверждения', 'outline'], posted: ['Подтверждено', 'default'], reversed: ['Сторнировано', 'destructive'], rejected: ['Отклонено', 'destructive'] };
const fmt = new Intl.NumberFormat('ru-RU', { style: 'currency', currency: 'RUB' });
const date = new Intl.DateTimeFormat('ru-RU', { dateStyle: 'medium', timeZone: 'Europe/Moscow' });
export async function get(path) { return request(() => fetch(path, { credentials: 'same-origin' })); }
export function Status({ value }) { const [label, variant] = status[value] || ['Требует проверки', 'outline']; return <Badge variant={variant}>{label}</Badge>; }
export function PageState({ title, subtitle, children, headingClassName = '' }) { return <><div className={`page-heading ${headingClassName}`}><h1>{title}</h1><p>{subtitle}</p></div>{children}</>; }
function UseData({ path, children }) { const [state, setState] = useState({ loading: true }); useEffect(() => { let live = true; get(path).then(data => live && setState({ data, loading: false })).catch(error => live && setState({ error, loading: false })); return () => { live = false; }; }, [path]); if (state.loading) return <div className="grid gap-4"><Skeleton className="h-28 rounded-2xl" /><Skeleton className="h-64 rounded-2xl" /></div>; if (state.error) return <Card><CardContent className="p-6 text-destructive">{state.error.message}</CardContent></Card>; return children(state.data); }
const registryColumns = [['Реестр', x => x.external_ref], ['Мерчант', x => x.merchant], ['Пополнено', x => fmt.format(x.total || 0)], ['Комиссия', x => fmt.format(x.commission || 0)], ['Статус', x => <Status value={x.status} />]];
const expenseColumns = [['Дата', x => x.payload?.date || date.format(new Date(x.created_at))], ['Тип', x => x.payload?.category || 'Не указан'], ['Сумма', x => fmt.format(x.payload?.amount || 0)], ['Статус', x => <Status value={x.status} />]];
const moneyColumns = [['Действие', x => x.kind], ['Сумма', x => fmt.format(x.payload?.amount || 0)], ['Создано', x => date.format(new Date(x.created_at))], ['Статус', x => <Status value={x.status} />]];
export function Registries() { return <PageState title="Реестры оплат" subtitle="Факт поступления подтверждается отдельно после проверки строк, суммы и комиссии."><UseData path="/api/registries">{rows => <List rows={rows} columns={registryColumns} empty="Реестров пока нет." />}</UseData></PageState>; }
export function Expenses() { return <PageState title="Расходы" subtitle="Денежное списание происходит только после подтверждения главным администратором."><UseData path="/api/drafts">{rows => <List rows={rows.filter(x => x.kind === 'expense')} columns={expenseColumns} empty="Расходов пока нет." />}</UseData></PageState>; }
export function Money() { return <PageState title="Движение денег" subtitle="Снятия, передачи, возвраты и отдельные решения по расхождениям."><UseData path="/api/drafts">{rows => <List rows={rows.filter(x => x.kind !== 'expense')} columns={moneyColumns} empty="Операций пока нет." />}</UseData></PageState>; }
export function Catalog() { return <PageState title="Справочники" subtitle="Мерчанты, карты, контакты, банки и ответственные. Здесь нет денежных проводок."><UseData path="/api/catalog">{catalog => <div className="grid gap-4 md:grid-cols-2">{[['Мерчанты', catalog.merchants, x => x.name], ['Карты', catalog.cards, x => x.mask], ['ФИО и телефоны', catalog.payment_contacts, x => x.full_name], ['Банки', catalog.banks, x => x.name], ['Ответственные', catalog.custodians, x => x.name]].map(([title, items = [], label]) => <Card key={title} className="rounded-2xl"><CardHeader><CardTitle className="text-lg">{title}</CardTitle><CardDescription>{items.length} записей</CardDescription></CardHeader><CardContent className="grid gap-2">{items.slice(0, 5).map(item => <div className="rounded-lg bg-muted px-3 py-2 text-sm" key={item.id}>{label(item)}</div>)}{items.length > 5 && <p className="text-sm text-muted-foreground">Показаны первые 5 записей.</p>}</CardContent></Card>)}</div>}</UseData></PageState>; }
export function Reports({ role }) { const [month, setMonth] = useState(new Date().toISOString().slice(0, 7)), [monthly, setMonthly] = useState(null), [error, setError] = useState(''), [busy, setBusy] = useState(false); async function loadMonth() { setBusy(true); setError(''); try { setMonthly((await get('/api/report?month=' + encodeURIComponent(month))).month); } catch (e) { setError(userError(e)); } finally { setBusy(false); } } async function approve() { if (!monthly) return; setBusy(true); setError(''); try { await request(() => fetch('/api/report/approve', { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json', 'X-CSRF': '1' }, body: JSON.stringify({ month: monthly.month, digest: monthly.digest }) })); await loadMonth(); } catch (e) { setError(userError(e)); setBusy(false); } } return <PageState title="Отчёты" subtitle="Показатели, движения и разницы из подтверждённых операций."><UseData path="/api/report">{report => <><div className="grid gap-4 md:grid-cols-2">{Object.entries(report.summary || {}).map(([key, value]) => <Card key={key} className="rounded-2xl"><CardContent className="p-6"><p className="text-sm text-muted-foreground">{key.replaceAll('_', ' ')}</p><strong className="mt-3 block font-mono text-2xl">{fmt.format(value || 0)}</strong></CardContent></Card>)}</div><Card className="mt-7 rounded-2xl"><CardHeader><CardTitle>Результат за месяц</CardTitle><CardDescription>Утверждается сохранённая версия отчёта. При изменении данных потребуется новый просмотр.</CardDescription></CardHeader><CardContent><div className="flex flex-wrap items-end gap-3"><label className="grid gap-2 text-sm font-medium">Месяц<Input type="month" value={month} onChange={e => setMonth(e.target.value)} /></label><Button type="button" onClick={loadMonth} disabled={busy}>{busy ? 'Загрузка…' : 'Показать'}</Button></div>{error && <Alert variant="destructive" className="mt-4"><AlertDescription>{error}</AlertDescription></Alert>}{monthly && <div className="mt-5 grid gap-3 md:grid-cols-4"><div className="rounded-xl bg-muted p-4"><p className="text-sm text-muted-foreground">Выручка</p><strong>{fmt.format(monthly.revenue || 0)}</strong></div><div className="rounded-xl bg-muted p-4"><p className="text-sm text-muted-foreground">Расходы</p><strong>{fmt.format(monthly.expenses || 0)}</strong></div><div className="rounded-xl bg-muted p-4"><p className="text-sm text-muted-foreground">Прибыль</p><strong>{fmt.format(monthly.profit || 0)}</strong></div><div className="rounded-xl bg-muted p-4"><p className="text-sm text-muted-foreground">Статус</p><strong>{monthly.approved ? 'Утверждён' : 'Ожидает'}</strong></div></div>}{monthly && role === 'accountant' && !monthly.approved && <Button className="mt-5" type="button" onClick={approve} disabled={busy}>Утвердить эту версию</Button>}</CardContent></Card></>}</UseData></PageState>; }
const auditColumns = [['Когда', x => date.format(new Date(x.at))], ['Действие', x => x.action], ['Кто', x => x.role], ['Результат', x => x.outcome === 'success' ? 'Выполнено' : 'Отклонено']];
export function Audit() { return <PageState title="История действий" subtitle="Подтверждения, исправления и отклонённые попытки сохраняются для проверки."><UseData path="/api/audit">{rows => <List rows={rows} columns={auditColumns} empty="История пока пуста." />}</UseData></PageState>; }
function List({ rows, columns, empty }) { return <Card className="overflow-hidden rounded-2xl"><CardContent className="p-0">{rows.length ? <div className="overflow-x-auto"><Table><TableHeader><TableRow>{columns.map(([label]) => <TableHead key={label}>{label}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((row, index) => <TableRow key={row.id || index}>{columns.map(([label, render]) => <TableCell key={label}>{render(row)}</TableCell>)}</TableRow>)}</TableBody></Table></div> : <p className="p-8 text-muted-foreground">{empty}</p>}</CardContent></Card>; }
